### ISSUE TITLE
Buy those sunglasses

### ISSUE THREAD

**Issue by cwienberg** [ynyway/new-year-new-yenny#1]
@ynyz

**Comment by ynyway** [comment]
HAHA
thank you so much OMG HAHAHAHAHHA ahhhhhhhhhh

**Comment by ynyway** [comment]
btw i want the ones that IU wears in [this](https://www.youtube.com/watch?v=m7mvpe1fVa4) music video 😭

**Comment by cwienberg** [comment]
I can't assign you

**Comment by cwienberg** [comment]
Those are cool shades

**Comment by ynyway** [comment]
how 2 put on milestone? how 2 put on board? is it todo? stretch? active?

**Comment by cwienberg** [comment]
@ynyz You missed the deadline

**Comment by ynyway** [comment]
NOOOOOOOOOOO

**Comment by cwienberg** [comment]
Bump

**Comment by ynyway** [comment]
I found sunglasses in my room last night
